### ISSUE TITLE
CVC-ClinicDB数据集上test.py，结果差距比较大

### ISSUE THREAD

**Issue by LWTvickyzz** [wurenkai/H-vmunet#3]
3090显卡，resume_model下载的，跑出来的结果差距比较大，请问是什么原因呢？
![Quicker_20240407_111756](https://github.com/wurenkai/H-vmunet/assets/35456947/169ecc5f-18b2-4edb-a99b-e36716f2f66e)

**Comment by wurenkai** [comment]
Hi, we just confirmed that the weight files are correct. We have uploaded a total of three weight files for three different datasets, did you modify the correct corresponding weight files when testing the CVC-ClinicDB dataset.
Also, you can check if there are any formatting issues with the data preparation by following the 'Prepare your own dataset' steps. I hope my answer can help you.
![test_CVC](https://github.com/wurenkai/H-vmunet/assets/124028634/1f8c431c-f63c-485f-bf70-e58404ef7cb1)

**Comment by wurenkai** [comment]
Also check that the image size is correctly resized to 256*256 when your data is prepared.

**Comment by Richard1Bob** [comment]
> Hi, we just confirmed that the weight files are correct. We have uploaded a total of three weight files for three different datasets, did you modify the correct corresponding weight files when testing the CVC-ClinicDB dataset.
> Also, you can check if there are any formatting issues with the data preparation by following the 'Prepare your own dataset' steps. I hope my answer can help you.

你训练了多久呢
